### ISSUE TITLE
refactor: Auth,User 페이지에 존재하는 Tabs 컴포넌트 리펙토링

### ISSUE THREAD

**Issue by perfumeplaylist** [prgrms-fe-devcourse/FEDC4_Campers_Jaeho#124]
## 요약

Auth,User 페이지에 존재하는 Tabs 컴포넌트 리펙토링

## 체크리스트

- [x] Auth,User 페이지에 존재하는 Tabs 컴포넌트 리펙토링

**Comment by sukvvon** [comment]
chakra ui를 활용한 알림창 진행하고 해주실 수 있나요? 오늘 마무리할 계획입니다!!

**Comment by perfumeplaylist** [comment]
넵 알겠습니다!

**Comment by sukvvon** [comment]
#200
#201 

마무리하였습니다!!
